version: 2.1

workflows:
  path_to_live:
    jobs:
      - sirius-api-gateway/unit_test_lambdas:
          name: unit_test_lambdas
      - sirius-api-gateway/package_lambda_artifact:
          name: package_lambda_artifact
          requires: [unit_test_lambdas]
      - sirius-api-gateway/build_gem_cache:
          name: build_gem_cache
      - sirius-api-gateway/lint_terraform:
          name: lint_terraform
          requires: [package_lambda_artifact]
      - sirius-api-gateway/build_api_test_file:
          name: build_api_test_file
          requires: [build_gem_cache]
      - sirius-api-gateway/apply_terraform:
          filters:
            branches:
              ignore: [master]
          name: apply_development
          workspace: development
          requires:
            [lint_terraform, build_gem_cache, package_lambda_artifact]
      - sirius-api-gateway/test_sirius_access:
          name: test_sirius_access
          requires: [apply_development]
      - sirius-api-gateway/newman_api_test:
          filters:
            branches:
              ignore: [master]
          name: test_lpas_collection_endpoint_development
          workspace: development
          requires: [build_api_test_file, apply_development]
      - sirius-api-gateway/apply_terraform:
          filters:
            branches:
              only: [master]
          name: apply_production
          workspace: production
          requires: [lint_terraform, build_gem_cache]
      - sirius-api-gateway/newman_api_test:
          filters:
            branches:
              only: [master]
          name: test_lpas_collection_endpoint_production
          workspace: production
          requires: [build_api_test_file, apply_production]
orbs:
  sirius-api-gateway:
    executors:
      ruby:
        docker: [image: circleci/ruby:latest-browsers]
      terraform:
        docker: [image: hashicorp/terraform]
      python:
        docker: [image: python:alpine]
      newman:
        docker: [image: postman/newman:alpine]
    commands:
      install_terraform:
        steps:
          - run:
              name: install_terraform
              command: |
                export TERRAFORM_VERSION=0.11.11
                export TERRAFORM_SHA256SUM=94504f4a67bad612b5c8e3a4b7ce6ca2772b3c1559630dfd71e9c519e3d6149c
                curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64.zip
                echo "${TERRAFORM_SHA256SUM}  terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > terraform_${TERRAFORM_VERSION}_SHA256SUMS
                sha256sum -c --status terraform_${TERRAFORM_VERSION}_SHA256SUMS
                sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /bin
                rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      relocate_lambda_packages:
        steps:
          - run:
              name: relocate_lambda_packages
              command: |
                mv /tmp/*.zip ~/project/
    jobs:
      lint_terraform:
        executor: terraform
        environment:
          TF_WORKSPACE: "development"
        steps:
          - checkout
          - restore_cache:
              keys:
                - lambda_artifact-{{ .Branch }}
          - relocate_lambda_packages
          - run:
              name: Init Terraform
              command: |
                terraform init
          - run:
              name: Lint Terraform
              command: |
                terraform validate
      build_gem_cache:
        executor: ruby
        steps:
          - checkout
          - restore_cache:
              keys:
                ['gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}']
          - run: bundle install --path vendor/bundle --quiet
          - save_cache:
              key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}
              paths: [vendor/bundle]
      apply_terraform:
        parameters:
          workspace:
            description: Terraform Workspace name
            type: string
            default: development
        environment:
          TF_WORKSPACE: "<< parameters.workspace >>"
        executor: ruby
        steps:
          - checkout
          - install_terraform
          - restore_cache:
              keys:
                - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}
          - restore_cache:
              keys:
                - lambda_artifact-{{ .Branch }}-{{ .Revision }}
          - relocate_lambda_packages
          - run: bundle install --path vendor/bundle --quiet
          - run: bundle exec rake terraform:apply
      unit_test_lambdas:
        executor: python
        steps:
          - checkout
          - run: pip3 install -r lambdas/requirements.txt -r lambdas/requirements-dev.txt --target ./lambdas/vendor
          - run: cd ./lambdas; python vendor/pytest.py --ignore=./vendor
      package_lambda_artifact:
        executor: python
        steps:
          - checkout
          - run: apk add zip
          - run: pip3 install -r lambdas/requirements.txt  --target ./lambdas/vendor
          - run: cd ./lambdas; zip -r9 /tmp/lambda_artifact.zip .
          - save_cache:
              key: lambda_artifact-{{ .Branch }}-{{ .Revision }}
              paths:
                - /tmp/lambda_artifact.zip
      build_api_test_file:
        executor: ruby
        steps:
          - checkout
          - restore_cache:
              keys:
                ['gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}']
          - run: bundle install --path vendor/bundle --quiet
          - run: bundle exec rake lambda:buildapitestfile
          - save_cache:
              key: api_test_config-{{ .Branch }}-{{ .Revision }}
              paths: /tmp/generated.postman_environment.json
      newman_api_test:
        parameters:
          workspace:
            description: Terraform Workspace name
            type: string
            default: development
        environment:
          TF_WORKSPACE: "<< parameters.workspace >>"
        executor: newman
        steps:
          - checkout
          - run: apk add ca-certificates -q
          - restore_cache:
              keys:
                - api_test_config-{{ .Branch }}-{{ .Revision }}
          - run: newman run https://www.getpostman.com/collections/c85538a8e4fb4f19b892 -e /tmp/generated.postman_environment.json
      test_sirius_access:
        executor: python
        steps:
          - run: pip3 install awscli
          - run: apk add jq
          - run:
              name: Login to AWS
              command: |
                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::288342028542:role/ci --role-session-name ci)
                export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                aws lambda invoke --invocation-type RequestResponse --function-name simulate_sirius_access --region eu-west-1 --log-type Tail outputfile.txt | jq -r '.LogResult'
